name = "exam-verse-registration-api"
main = "src/worker.js"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "EXAMVERSE_DB"
database_name = "exam-verse"
database_id = "18a1dd92-0e88-48cd-816b-9049620e21c6"
